### PR TITLE
Refactor poll_oneoff on Unix for easier implementation on Windows.

### PR DESCRIPTION
**Pull request by marmistrz**
I'd like to merge it before we land any kind of socket-related code. The absence of non-regular files on Windows makes it much easier to implement `poll_oneoff` on Windows.

Tasks:
* [x] Refactor the code to share common parts across platforms
* [ ] Actually implement `poll_oneoff` on Windows.

### CODE REVIEW

**Comment by kubkon** [comment]
@marmistrz could you put the refactoring bit on hold until #137 lands? I envision some major changes to come out of that and wouldn't want you to spend too much time on refactoring potentially dead code.

**Comment by marmistrz** [comment]
@kubkon yes. I've just realized that my Windows implementation is kind of blocked by #137 too.

**Comment by kubkon** [comment]
> @kubkon yes. I've just realized that my Windows implementation is kind of blocked by #137 too.

Yeah, my apologies for that! I'll try to merge #137 ASAP so as not to block you! :-)

**Comment by marmistrz** [comment]
Closing in favor of #137.

**Pull request closed without merging**
