### PR TITLE
 Reuse errno_from_ioerror to simplify error handling 

### PR DESCRIPTION
**Pull request by marmistrz**
This PR bases on #42.

### CODE REVIEW

**Comment by kubkon** [comment]
LGTM! If you don't mind, I'd like to have #41 squashed and rebased onto master first, before we proceed with this one. Is that OK with you? :-)

**Comment by marmistrz** [comment]
ok :)

**Comment by kubkon** [comment]
@marmistrz OK, so #41 is now merged. Could you rebase and apply your refactoring to anything that's either new or missed? :-)

**Comment by marmistrz** [comment]
I updated the change

**Comment by kubkon** [comment]
Great, thanks!

**Pull request merged**
