### PR TITLE
Fix filestat_from_nix conversion fn

### PR DESCRIPTION
**Pull request by kubkon**
Fixes bug uncovered in #65.

I think that in the long run we should consider utilising [filetime](https://github.com/alexcrichton/filetime), but this would require adding an extension trait so that we can set and get {a,c,m}times from `(&File, &Path)` pairs as well (essentially allowing for *at syscalls). @alexcrichton do you think it would be valid to extend `filetime` with such functionality for *nix hosts?

### CODE REVIEW

**Comment by kubkon** [comment]
cc @sunfishcode @marmistrz

**Comment by alexcrichton** [comment]
Hm I'm not sure I fully understand, what would be added to `filetime`? (it's probably reasonable to add I'm just curious)

**Comment by kubkon** [comment]
@alexcrichton Oh sorry for not explaining myself very well! Currently in `filetime` we can set/get times from handles such as `&File`. For WASI on *nix hosts, it'd be very useful to permit for `openat`-style calls, so then `&File` handle would point to a directory and `&Path` to a path relative to that handle. I'm just worried that representing open handle to a directory wrapped in `&File` would not be very clear from the interface perspective to the crate's user; that is, it could cause confusion where users would supply a handle to an actual file and not a directory, but perhaps the very same problem is still faced in raw syscalls to `openat`-style functions.

**Review by marmistrz — APPROVED** [review]
What a nasty bug! Thanks for catching that.

**Comment by marmistrz** [comment]
> I'm just worried that representing open handle to a directory wrapped in &File would not be very clear from the interface perspective to the crate's user; that is, it could cause confusion where users would supply a handle to an actual file and not a directory, but perhaps the very same problem is still faced in raw syscalls to openat-style functions.

@kubkon it may cause confusion, but the `openat`-style functions are very confusing themselves. I didn't understand why in world one would want such syscalls until I read `openat(2)` :P

**Comment by alexcrichton** [comment]
@kubkon sounds reasonable to me to add!

**Comment by kubkon** [comment]
@marmistrz that’s a fair enough actually. I sometimes also find `openat`-style functions confusing :-)

@alexcrichton great! Let’s merge these changes as they are for now, with the intention of enabling the `openat`-style functionality in `filetime`, which I’ll do my best to add in the near future :-)

**Comment by sunfishcode** [comment]
Sounds good!

**Pull request merged**
