### PR TITLE
Implement fd_readdir on Unix with nix & on Windows with libstd

### PR DESCRIPTION
**Pull request by marmistrz**
Before this can be merged:
* [x] we need to clarify and extend the test in https://github.com/CraneStation/wasi-misc-tests/pull/21. 
* [ ] On Unix, raw `readdir` executed on an empty directory will return two entries: `.` and `..`. On the other hand, `std::fs::read_dir` will return an empty iterator. Should we emulate the behavior of the unix `readdir` syscall in wasi by manually adding `.` and `..`? The current implementation does it but the spec is not clear about this. 
* [ ] we're leaking inode/serial number information about `..`, which may not be preopened and may hence be inaccessible for apps run inside WASI. I don't think it's an issue, but I want to make sure this isn't a vulnerability
* [ ] upstream the changes done for nix (tracking in https://github.com/nix-rust/nix/issues/1110)
* [ ] mac is currently broken
-----
Follow-ups needed:
* Add a heuristic optimization to `fd_readdir` on Windows: the most common use case where seeking may be needed is when the buffer length is insufficient. We could cache the last cookie and the relevant handle for each file descriptor so that the implementation is O(n) and not O(n^2) with O(1) buffer in the most common case
* Add `Into`/`From` conversions for `Filetype` 
* Raise the issues about the spec  of `fd_readdir`:
  * `readdir(3p)` says that 
     > If a file is removed from or added to the directory after the most recent call to  opendir()  or
     > rewinddir(),  whether  a subsequent call to readdir() returns an entry for that file is unspecified.

    We need to add this to spec of `fd_readdir` in some form.
  * discuss how to clarify the semantics of cookie (also that it corresponds to the next entry)
  * mention the similarity to `readdir`/`seekdir` in the docs
  * should the implementation return  `.` & `..`?
  * be precise whether or not the filenames are NULL-terminated (in POSIX they are)
* ~nix uses `readdir_r` which is deprecated in `readdir_r(3)`. Raise an issue and discuss whether or not `readdir` should be used instead (at least on Linux)~ https://github.com/rust-lang/rust/issues/34668
-------
**Implementation notes:**
The code written using libstd could be mostly reused for Linux, but:
* (first and foremost) this would force us to emulate entries for `.` & `..`, which would cost us extra syscalls on Linux
* accessors for `file_serial_no` not stable yet: https://github.com/rust-lang/rust/issues/63010
* `ReadDir` from `libstd` requires to have a `Path` for no real reason.

While we could technically either hack the `std::fs::ReadDir` using unsafe code (transmute) or fork it, I believe that the overhead of adding at least two (and probably at least four) extra syscalls 

`ReadDir` can only be constructed from a root path for the directory query.

On Unix, the path is only used for `impl Debug` and `fn path`. In other words, `fd_readdir` could be implemented completely using `std::fs::ReadDir` if we just removed every reference to the root path in the code and created it from a `&File` instead. Unfortunately, this wouldn't be a backwards compatible change in libstd, because `fn path` would have to return an `Option<Path>`.

On Windows, while the root path is used in `impl Iterator for ReadDir`, it's only seeming that the restriction is required, since one can recover path from `&File` on Windows. 

Therefore, to all my knowledge it appears that the explicit path could be removed from `ReadDir`, but it would break backwards compatibility, so such a change won't unfortunately be accepted into stdlib.

-------
What are the alternatives?
* we could manually create our own `ReadDir` and then use `std::mem::transmute` to convert it to `std::fs::ReadDir`. While this will work, it is heavily dependent on non-public Rust libstd API and its implementation details. We'd also probably have to do our own wrapper to disallow `DirEntry::path`
* do a copy-paste of `ReadDir` (possibly in a separate crate), dropping the requirement on `Path`. This has the obvious disadvantage of maintaining our own fork but allows us to have a common implementation for Unix & Windows. We can't actually reuse the `readdir` syscall on Unix because of implementation details: on Unix the filenames are null-terminated, on wasi they aren't (cf. the discussion in https://github.com/CraneStation/wasi-misc-tests/pull/21)
* implement `fd_readdir` using `nix` on unix, `ReadDir` on windows.

### CODE REVIEW

**Comment by kubkon** [comment]
@marmistrz have a look at WebAssembly/WASI#61 at some discussion about `fd_readdir` impl on Windows hosts.

**Comment by marmistrz** [comment]
It looks like upstreaming the changes to nix is a non-trivial task. I think the best idea is to currently "fork" the readdir module from nix and make the changes locally in our source tree (i.e. add ` src/sys/unix/hostcalls_impl/dir.rs`). Are you okay with that?

**Comment by sunfishcode** [comment]
To make sure I'm not missing something, is this PR subsumed by #116?

**Comment by kubkon** [comment]
> To make sure I'm not missing something, is this PR subsumed by #116?

That's the idea, yep.

**Comment by kubkon** [comment]
It actually might make sense to close it manually now so as to avoid any future confusion.

**Comment by marmistrz** [comment]
Yes, no further work will happen on this branch.

**Pull request closed without merging**
